name: called-wf

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      flavor:
        required: true
        type: string
      upgrade-flavors:
        required: true
        type: string

jobs:
  called-wf:
    runs-on: ubuntu-latest
    if: contains(inputs.upgrade-flavors, inputs.flavor) || inputs.type == 'install'
    steps:
      - name: echo inputs
        run: |
          echo "type: ${{ inputs.type }}, flavor: ${{ inputs.flavor }}, upgrade-flavors: ${{ inputs.upgrade-flavors }}"
      - name: some test
        run: echo tests
