name: Verify

on:
  pull_request:

jobs:
  skip-check:
    runs-on: ubuntu-latest
    steps:
      - name: Skip check
        id: skip-check
        run: echo 'TESTEDFLAVORS=["upstream","unicorn"]'' >> "$GITHUB_OUTPUT"
    outputs:
      TESTEDFLAVORS: ${{ steps.skip-check.outputs.TESTEDFLAVORS }}
  verify:
    needs: skip-check
    strategy:
      fail-fast: false
      matrix:
        type: [install, upgrade]
        flavor: [upstream, registry1, unicorn]
    uses: ./.github/workflows/called.yaml
    with:
      type: ${{ matrix.type }}
      flavor: ${{ matrix.flavor }}
      tested-flavors: ${{ needs.skip-check.outputs.TESTEDFLAVORS }}