name: Verify

on:
  pull_request:

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        type: [install, upgrade, breaking-change]
        flavor: [upstream, registry1, unicorn]
    uses: ./.github/workflows/called.yaml